[[edge_functions]]
function = "eleventy-edge"
path = "/*"

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "style-src 'unsafe-inline'; script-src-elem 'unsafe-inline' 'self';"

[dev]
targetPort = 8088
