[[edge_functions]]
function = "eleventy-edge"
path = "/*"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; style-src 'unsafe-inline' 'self';"

[dev]
targetPort = 8088
